name: Deploy to Test Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to cPanel
      run: |
        ssh tmuac1@tmu.ac.in 'cd /home/tmuac1/hospital-website && git pull origin main '
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ssh-key }}